/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_janik_Main */

#ifndef _Included_de_janik_Main
#define _Included_de_janik_Main
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     de_janik_Main
	* Method:    GetInt
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_de_janik_Main_GetInt
		(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
